DEGREES = [
    "b.tech",
    "btech",
    "b.e",
    "be",
    "m.tech",
    "mtech",
    "m.e",
    "me",
    "b.sc",
    "bsc",
    "m.sc",
    "msc",
    "phd",
    "doctor of philosophy",
    "mba",
    "bca",
    "mca",
    "b.com",
    "m.com",
    "Bachelor of Technology",
    "B.Tech",
    "Bachelor of Engineering",
    "B.E.",
    "Master of Technology",
    "M.Tech",
    "Bachelor of Science",
    "B.Sc",
    "Master of Science",
    "M.Sc",
    "Bachelor of Computer Applications",
    "BCA",
    "Master of Computer Applications",
    "MCA"
]